Refactoring project configuration
healthysustainablecities/global-indicators pull request #30
Opened 2020-04-03 14:32 UTC by shiqin-liu

- update how to contribute 

- scripts are updated to address the input and output file issue in response to #20 

- propose a way to refactor project config in [setup_config.py](https://github.com/shiqin-liu/global-indicators/blob/master/process/setup_config.py)

2020-04-03 17:05 UTC, gboeing requested changes

2020-04-03 17:05 UTC, gboeing commented on process/aggr.py
> +from setup_aggr import * # module for all aggregation functions used in this notebook
As a general namespace "best practice" I'd recommend `import setup_aggr as sa` and then referring to its functions in this script like `sa.function_name()`. It helps to see where individual things come from.

2020-04-03 17:05 UTC, gboeing commented on process/aggr.py
> +from setup_config import * # import project config parameters
same as previous comment

2020-04-03 17:05 UTC, gboeing commented on process/setup_config.py
> +to_crs = [7845, 2193, 32618, 32647, 25831, 29902, 32633, 32644,
I might recommend combining `cities`, `regions`, and `to_crs` lists into a single list of dicts, like `cities = [{'name':'adelaide', 'region':'au', 'crs':'epsg:7845'}, etc.]`

2020-04-03 17:05 UTC, gboeing commented on process/sp.py
> +from setup_config import * # import project config parameters
See earlier namespace management comments about just importing the module rather than importing * from it.

2020-04-03 17:05 UTC, gboeing commented on process/sp.py
> -        gpkgPath, layer=config["parameters"]["samplePoints"])
There appears to be some inconsistency throughout with using either single quotes `'` vs double quotes `"`... I'd suggest standardizing around single quotes.

2020-04-03 17:06 UTC, gboeing commented
@shiqin-liu I took a look through this PR and made some suggestions. I did not inspect the notebook files' diffs, as they are pretty hard to read (due to their json-wrapped nature).

2020-04-07 18:36 UTC, gboeing commented
@shiqin-liu whenever you're ready for me to re-review, just add some comments to the individual conversations I opened in the review (or resolve them if they're just done) then @ me.

2020-04-07 19:45 UTC, shiqin-liu commented
> @shiqin-liu whenever you're ready for me to re-review, just add some comments to the individual conversations I opened in the review (or resolve them if they're just done) then @ me.

Thanks @gboeing, I think my last update has resolved the comments above, and ready to be re-reviewed

2020-04-07 20:30 UTC, gboeing approved these changes

2020-04-07 20:31 UTC, gboeing commented
@shiqin-liu this looks good to me. @carlhiggs do you have any final comments prior to merge?

2020-04-10 00:14 UTC, merged

2020-04-10 00:14 UTC, gboeing commented
@shiqin-liu this has been merged