Fix edge_validation bugs
healthysustainablecities/global-indicators pull request #71
Opened 2020-07-22 03:56 UTC by nicholas-david

Now able to fully run edge_validation

2020-07-22 03:57 UTC, nicholas-david commented
@gboeing just had to update some configs. Now able to run edge validation totally. Took about 3 hours to complete.

2020-07-22 15:42 UTC, gboeing requested changes

2020-07-22 15:42 UTC, gboeing commented on .gitignore
> +>>>>>>> ce1e438213a8d6f8ba8122e130c70d57df6399bc
It looks like this merge conflict needs to be resolved.

2020-07-23 01:19 UTC, nicholas-david commented
@gboeing SHould be good

2020-07-23 01:49 UTC, merged